import {s} from './variables'
Cypress.Commands.add('responseApi', (address)=>{
    cy.request(`${Cypress.env('api_accounts')}/${address}`)
      .then(r=>{
        let body = JSON.parse(r.body.account.mosaics[0].amount)
        let res = body.toString()
        let fin_num = res.slice(0, 1) +','+res.slice(1, 4)+'.'+res.slice(-6)
        while(fin_num.slice(-1)=='0'){
          fin_num = fin_num.slice(0, -1)
        }
        return fin_num
      })
})

Cypress.Commands.add('importSimpleAcc', (name, pass, mnem, address) => {
    cy.contains('Import mnemonic').click()
    cy.get(s.profile_name_field).type(name)
    cy.get(s.network_type_selector).click()
    cy.contains('Symbol Testnet').click()
    cy.get(s.password_create_acc_field).type(pass)
    cy.get(s.confirm_password_create_acc_filed).type(pass)
    cy.contains('Next').click()
    cy.get(s.mnemonic_field).type(mnem)
    cy.contains('Next').click()
    cy.responseApi(address).then(resp=>cy.get(s.balance_address_to_interact).should('have.text', resp))
    cy.get(s.first_address).click()
    cy.get(s.second_address).click()
    cy.responseApi(address).then(resp=>cy.get(s.balance_selected_account).should('have.text', resp))
    cy.contains('Next').click()
    cy.get(s.accept_checkbox).check()
    cy.contains(' Finish ').click()
    cy.responseApi(address).then(resp=>cy.get(s.balance_xym).should('have.text', resp))
    cy.responseApi(address).then(resp=>cy.get(s.balance_assets).should('have.text', resp))
})

Cypress.Commands.add('importMultisigAcc', (name, pass, mnem, address) => {
  cy.contains('Import mnemonic').click()
  cy.get(s.profile_name_field).type(name)
  cy.get(s.network_type_selector).click()
  cy.contains('Symbol Testnet').click()
  cy.get(s.password_create_acc_field).type(pass)
  cy.get(s.confirm_password_create_acc_filed).type(pass)
  cy.contains('Next').click()
  cy.get(s.mnemonic_field).type(mnem)
  cy.contains('Next').click()
  cy.responseApi(address).then(resp=>cy.get(s.balance_address_to_interact).should('have.text', resp))
  cy.get(s.first_address).click()
  cy.get(s.second_address).click()
  cy.get(s.third_address).click()
  cy.get(s.fourth_address).click()
  cy.responseApi(address).then(resp=>cy.get(s.balance_selected_account).should('have.text', resp))
  cy.contains('Next').click()
  cy.get(s.accept_checkbox).check()
  cy.contains(' Finish ').click()
  cy.responseApi(address).then(resp=>cy.get(s.balance_xym).should('have.text', resp))
  cy.responseApi(address).then(resp=>cy.get(s.balance_assets).should('have.text', resp))
})
