version: "3"
services:
  kill-api-nodes-random:
    image: gaiaadm/pumba
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level=debug --json --random  --interval 3m kill --limit 1 --signal SIGKILL 're:([A-Za-z0-9_])*api-node-(broker-){0,1}[\d+]*'"
    # Find containers like bootstrap_api-node-0 or bootstrap_api-node-broker-0 etc.
