version: "2"
services:
  # chaos commands
  chaos-kill-peer-node-0:
    image: gaiaadm/pumba
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level debug --interval 3m kill --signal SIGKILL bootstrap_peer-node-0_1"
  chaos-kill-peer-node-1:
    image: gaiaadm/pumba
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level debug --interval 2m kill --signal SIGKILL bootstrap_peer-node-1_1"
