---
- hosts: all:!spammer*
  gather_facts: no
  tasks:
  - name: docker-compose up all symbol containers
    shell: |
      cd ~/symbol-testnet/{{type}}
      docker-compose up -d --build
  - name: get symbol containers status
    shell: |
      cd ~/symbol-testnet/{{type}}
      docker-compose ps
    register: result
  - debug:
      var: result
