---
- hosts: all:!spammer*
  gather_facts: no
  tasks:
  - name: ensure all symbol containers are running
    shell: |
      cd ~/symbol-testnet/{{type}}
      docker-compose start
  - name: get symbol containers status
    shell: |
      cd ~/symbol-testnet/{{type}}
      docker-compose ps
    register: result
  - debug:
    var: result
