---
- hosts: all:!spammer*
  gather_facts: no
  tasks:
  - name: symbol status
    shell: |
      cd /home/ubuntu/symbol-testnet/{{type}}
      docker-compose ps
    register: result
  - debug:
      var: result
