---
- hosts: all:!spammer*
  gather_facts: no
  tasks:
  - name: symbol up
    shell: |
      cd ~/symbol-testnet/{{type}}
      docker-compose up -d --build
  - name: symbol status
    shell: |
      cd ~/symbol-testnet/{{type}}
      docker-compose ps
    register: result
  - debug:
      var: result
