# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build e2e tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check gradle version
      uses: madhead/check-gradle-version@v1
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Symbol Direct Java SDK project
      run: ./gradlew --project-dir symbol-direct-java-sdk/ --refresh-dependencies --rerun-tasks clean classes javadocJar
    - name: Build Symbol end-to-end tests project
      run: ./gradlew --project-dir symbol-e2e-tests/ --refresh-dependencies --rerun-tasks clean testClasses
